name: Automate Preprocessing

on:
  push:
    branches: [ main, master ]
    paths:
      - 'dataset/**'
      - 'automate_Muhamad-Saefuloh.py'
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run preprocessing script
        run: |
          python automate_Muhamad-Saefuloh.py

      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v3
        with:
          name: preprocessed-dataset
          path: preprocessed_corn_data.csv

      - name: Commit preprocessed data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add preprocessed_corn_data.csv
          git diff --staged --quiet || git commit -m "auto: update preprocessed_corn_data.csv [skip ci]"
          git push
